# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: CodeCraftStudio.AutoDownloadSorter
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: CodeCraft Studio
PackageName: Auto Download Sorter
License: MIT
Copyright: Copyright (C) 2023 CodeCraft Studio
ShortDescription: Auto Download Sorter Installer
ManifestType: defaultLocale
ManifestVersion: 1.5.0
